### ISSUE TITLE
Crystal Item Update

### ISSUE THREAD

**Issue by gabeernie** [hellaspooks/Sorcery#53]
Rename crystals: currently, crystals are added with just their name (e.g. chalcedony, serpentine...),  change crystal items to be added as crystal_name (crystal_chalcedony etc.) to match the naming system for the asset files.

Update Crystal Textures with current versions in dropbox.

**Comment by AidanNaut** [comment]
Working on this one now.

**Comment by AidanNaut** [comment]
Should be good to go.
